INSERT INTO TODO_USER (ID, USERNAME, FIRST_NAME, LAST_NAME, CREATE_DATE, MODIFY_DATE, DEACTIVATION_DATE, STATUS)
VALUES (1, 'clarke', 'Clarke Benedict', 'Plumo', SYSDATE, SYSDATE, SYSDATE, 1);

INSERT INTO TODO_USER (ID, USERNAME, FIRST_NAME, LAST_NAME, CREATE_DATE, MODIFY_DATE, DEACTIVATION_DATE, STATUS)
VALUES (2, 'let', 'Hunneleth', 'Villalon', SYSDATE, SYSDATE, SYSDATE, 1);

INSERT INTO TODO_USER (ID, USERNAME, FIRST_NAME, LAST_NAME, CREATE_DATE, MODIFY_DATE, DEACTIVATION_DATE, STATUS)
VALUES (3, 'cyst', 'Francis', 'Mago', SYSDATE, SYSDATE, SYSDATE, 1);

INSERT INTO TODO_TASK (ID, TITLE, DESCRIPTION, STATUS)
VALUES (1, 'Study Clean Code', 'Via teacher', 0);

INSERT INTO TODO_TASK (ID, TITLE, DESCRIPTION, STATUS)
VALUES (2, 'Study Clean Architecture', 'Via example', 0);

INSERT INTO TODO_TASK (ID, TITLE, DESCRIPTION, STATUS)
VALUES (3, 'Study Clean Coder', 'Via experience', 1);
